<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                "id" => null,
                "nama_guru" => "Atik Restusari, S.Pd., M.Pd.",
                "nip" => "196812312005012003",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Sri Indriyati, S.Pd., M.Pd.",
                "nip" => "197409212005012001",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "H. Sjamsul Huda, S.Si.",
                "nip" => "197002212005011002",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Sumarno, S.Pd.",
                "nip" => "197405031999031002",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Dra. Palupi Widiati",
                "nip" => "196808202005012001",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Nikmattulloh, S.Pd.",
                "nip" => "197002032005011003",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Tri Hidayat, S.Pd.",
                "nip" => "198002282005011004",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Rina Handayani, S.Pd.",
                "nip" => "196903202005012001",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Dra. Hj. Yaniatun",
                "nip" => "196601182005012002",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Suharto, S.Pd.",
                "nip" => "197111292005011002",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Sholikhan, S.Pd.",
                "nip" => "197006212003121002",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Hj. Nurlaeli, S.Pd.",
                "nip" => "196712262005012001",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Ratna Erawati, S.Pd.",
                "nip" => "197304282006042015",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Hj. Siti Chafsoh, S.Ag.",
                "nip" => "196811252006042012",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Minan Ruspriyadi, S.Pd.",
                "nip" => "197309072007011024",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Dewi Ida Yani, S.Pd., M.Pd.",
                "nip" => "197801262007012012",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Intan Winarsih, S.Pd.I.",
                "nip" => "198003132007012025",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Trisni Retnowati, S.P., S.Pd.",
                "nip" => "198103162007102002",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Siti Imamah, S.Ag.",
                "nip" => "197608042009122003",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Moh. Fahim, S.Ag.",
                "nip" => "197110232007011024",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Romlan, S.Pd.I.",
                "nip" => "197808312007101001",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Marno, S.Pd.I.",
                "nip" => "197311072007011026",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Agus Sunarso, S.H.",
                "nip" => "198808072019031013",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Rastri Izzah Nastiti, S.Pd.I.",
                "nip" => "199202082019032024",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Sri Setiyaningsih, S.Pd.",
                "nip" => "198704142019032013",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Pipit Bakhtiar, S.Pd.",
                "nip" => "198312012019031005",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Fitri Afniati, S.Pd.",
                "nip" => "199004082023212044",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Wahidun, S.Pd.I.",
                "nip" => "198003102023211009",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Dwi Novianingsih, S.Si.",
                "nip" => "198111192023212018",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Umi Sangidah, S.E.",
                "nip" => "197909152024212004",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Hafid Afridian, S.Pd.",
                "nip" => "199304112025051003",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Marizka Noviana Dewi, S.Pd.",
                "nip" => "199911022025052007",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Sita Pradhita Nuraida, S.Pd.",
                "nip" => "199207122025052006",
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Muhammad Yusuf Rabil, S.Hum.",
                "nip" => "200005022025051006",
                "kelamin" => "L",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Hj. Khis Fakhriyati, S.Pd.",
                "nip" => null,
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => null,
                "nama_guru" => "Imroatun Najihah, S.Pd.",
                "nip" => null,
                "kelamin" => "P",
                "is_active" => true,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ];

        $incId = 1;
        foreach($data as $x => $item) {
            $data[$x]["id"] = $incId;
            $incId++;
        }

        DB::table('guru')->delete();
        DB::table('guru')->insert($data);
    }
}
